### ISSUE TITLE
The promise returned from PersistentQueue#add never resolves with a non-undefined `id`

### ISSUE THREAD

**Issue by laser** [damoclark/node-persistent-queue#19]
## Problem

The `PersistentQueue#add` method returns a promise. When that promise resolves without error, it resolves to `undefined` because `this.id` is never set:

https://github.com/damoclark/node-persistent-queue/blob/5bce376702bb99b3418f6e041fd199a44655cf74/index.js#L380

Also, the the `this.lastID` property is never set, which means `this.emit('add', { id: this.lastID, job: job }) ;` will result in an `undefined` `id`, too.

**Comment by laser** [comment]
I've put up a PR to address this issue (plus a test) here:

https://github.com/damoclark/node-persistent-queue/pull/20

**Comment by damoclark** [comment]
Thanks very much for your contribution @erin I've published your fix.

Cheers,
Damo.

**Comment by laser** [comment]
@damoclark - No problemo. Thanks for writing this software so that I didn't have to!

Also, forgive my ignorance (I know very little about the Node.js ecosystem): Will I be able to acquire the newly-patched version of your library via NPM sometime soon?

**Comment by damoclark** [comment]
Well spotted bug by the way.  

> Also, forgive my ignorance (I know very little about the Node.js ecosystem): Will I be able to acquire the newly-patched version of your library via NPM sometime soon?

Yep.  I've published the changes to npm already.  

You can update your codebase from npm now.

D.
